name: Run Staging Migration Reminder

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - '*.js'

jobs:
  merge_job:
    # this job will only run if the PR has been merged
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: comment PR
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: 'Remember to run the migration file against staging! `(cd src/models && npx sequelize-cli db:migrate --env staging)`'
